modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"
issueTrackerURL = "https://github.com/Narratimo/HappyHttpMod/issues"

[[mods]]
modId = "eirarelay"
version = "${version}"
displayName = "Eira Relay"
authors = "Eira"
description = '''
HTTP automation mod for Minecraft. Connect your Minecraft world to external services via HTTP webhooks.
'''

[[mixins]]
config = "eirarelay.neoforge.mixins.json"

[[dependencies.eirarelay]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.eirarelay]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"
